### ISSUE TITLE
[Question] Can' t launch on mac with instructions in the readme

### ISSUE THREAD

**Issue by BoykoAlex** [YattaSolutions/org.eclipse.swt.browser.electron#5]
When i launch the final JAR i get:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
        no swt-win32-4946r21 in java.library.path: [/Users/aboyko/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
        no swt-win32 in java.library.path: [/Users/aboyko/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
        no swt in java.library.path: [/Users/aboyko/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
        Can't load library: /Users/aboyko/.swt/lib/macosx/x86_64/libswt-win32-4946r21.jnilib
        Can't load library: /Users/aboyko/.swt/lib/macosx/x86_64/libswt-win32.jnilib
        Can't load library: /Users/aboyko/.swt/lib/macosx/x86_64/libswt.jnilib

        at org.eclipse.swt.internal.Library.loadLibrary(Library.java:348)
        at org.eclipse.swt.internal.Library.loadLibrary(Library.java:257)
        at org.eclipse.swt.internal.C.<clinit>(C.java:19)
        at org.eclipse.swt.widgets.Display.<clinit>(Display.java:146)
        at de.yatta.browser.electron.App.start(App.java:33)
        at de.yatta.browser.electron.App.main(App.java:28)
```

I don't seem to have files such as `libswt.jnilib` on my mac... Seems like starting eclipse for the first time (or with `-clean`) should have created those 3 files but i still don't see them.
Any idea what i can do to fix this?

**Comment by l3-g5** [comment]
Hi Alex,
sorry, this was currently only tested with Windows. In the `pom.xml`, there are also commented entries for the SWT dependency for Linux and Mac. You need to replace the Windows entry with the Mac one. In `de.yatta.browser.electron.ElectronBrowserCanvas.unzipAndStartElectron()` there is also still a comment that a few lines need adaption for Linux and Mac. You have to use the correct name for the zip file and the executable there. I will test under Linux and Mac and make those places more generic the next days.

**Comment by BoykoAlex** [comment]
I have managed to launch the app on mac.
Changes:
- **pom.xml**
```
      <dependency>
         <groupId>org.eclipse.platform</groupId>
         <artifactId>org.eclipse.swt.cocoa.macosx.aarch64</artifactId>
         <version>${swt.version}</version>
      </dependency>

```
- **ElectronBrowserCanvas.java**
```
         unzip(getClass().getResourceAsStream("/headless-electron-darwin-x64-0.0.1.zip"), tempDir);
         ProcessBuilder processBuilder = new ProcessBuilder(tempDir + File.separator + "headless-electron.app/Contents/MacOS/headless-electron");
```

However, when launched **google.com** not even initial page renders. The shell is just blank white. I don't see any errors in the log. Only see `Open Connection`
Same happens if I switch dependency in the pom to `org.eclipse.swt.cocoa.macosx.x86_64`
Note that I'm on on the latest M1 mac hence something might be off.

I have also tried this on Windows 10. I was able to launch the app properly, it rendered pages however the XtermJS terminal experience was so-so unfortunately (See #6 )

**Comment by l3-g5** [comment]
I tried to start the app on Mac with the following code:
`Runtime.getRuntime().exec("open " + tempDir + File.separator + "headless-electron.app");
`
It crashes with the following error message:
